version: '3.4'

services:
  locationdb:
    container_name: locationdb
    restart: always
    ports:
      - "6378:6379"

  locationsql:
    container_name: locationsql
    environment:
        SA_PASSWORD: "Admin1234!"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  locationapi:
    container_name: locationapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Redis=locationdb:6379"
      - "ConnectionString:Server=locationsql;Database=LocationAPI;User Id=sa;Password=Admin1234!;TrustServerCertificate=true;"
    depends_on:
    - locationdb
    - locationsql
    ports:
      - "7000:80"