version: '3.4'

services:
  locationdb:
    container_name: locationdb
    restart: always
    ports:
      - "6378:6379"

  locationsql:
    container_name: locationsql
    environment:
      SA_PASSWORD: Admin1234!
      ACCEPT_EULA: Y
      UserID: "sa"
    ports:
      - "1432:1433"
    #volumes:
    #- ~/docker/sql/mssql/:/var/opt/mssql/
    #- ~/docker/sql/sqlserver/:/var/opt/sqlserver/ 

  locationapi:
    container_name: locationapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Redis=locationdb:6379"
      - "ConnectionString:Server=locationsql:1432;Database=LocationAPI;User Id=sa;Password=Admin1234!;TrustServerCertificate=true"
    depends_on:
    - locationdb
    - locationsql
    ports:
      - "7000:80"