version: '3.4'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    container_name: locationdb
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: admin1234
      ACCEPT_EULA: Y
      UserID: "sa"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data

  locationapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis:redis:6379
    depends_on:
      - redis
    ports:
      - "8000:80"

volumes:
    redis_data:
